travis:
  secure:
    BINSTAR_TOKEN: OAHXDNcuN7LAi8ff1IiZ7d9WjF/iixZeJXEl7MdZeHHrNvpBlfmqf2b6/Ya6dBeQDSmc+yRMA8AVHY5Cgcxp9enDiBPBbTsUV3zitWwdDjZb10R0us1TqtGlzPRQuOsr/6EL7w/az++s2eyJvfk5i/l1MR6scgCH7VuPmYkwj7H1uEC7UYC3HZtaOnxCc1L6PpsG5BlGCMYZeY58p2b58hBbOKD/Zq4t95SO02YEjcS7oy4T3YY4/ASWUoB8FVNRDYpBEVFwfBYFIgSS6rVRwiIy9VAuuLju2rBU634IKWGOMS/019ZHVoIK3xThJJaA2n4yVQ+3lbzi03kRWf8EO3XqHvWKbELyyW+Y/mTJ+/8V8BW42R8Q8AdWrad//xWorT/B34BZPLbhdI7tNHz0n/b9SclQKUGHKQMFniV3iiAxfUZyYbw7aFoG+qG6fpWIN7CCyLecvlcTKCQ6lj5XwUQJQvNPcOVLdh74Gw22g1vKTw5JbBKHtlVvZKIWpKrLdOkzwPcuizzH7WweM+12sSHdMt//iO1hOFBFR/T0A7gLloY9VphZn2Ir/92rt4EdAC4N7bi7uWOlx963DE/M6cg5cbbyr2vgGkFXiKTX/oqbwSIspJ+/Ki9lr0Y2UrYA6Lz+vqgZz7i7bkpzOyI6IpgKtyyCelCHGXzx6KHz10Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
